confName: My workflow
event: []
job:
  - name: Job1
    steps:
      - name: Step1
        type: shell
        command: echo "Hello, Shantou"
      - name: Step2
        type: shell
        command: $SHANTOU_SECRET/$ID_VALUE
      
