name: Mon super workflow
on: [push] # action évènement
jobs: 
  say-hello: # nom du job
    runs-on: ubuntu-latest # environnement 
    steps:  
      - run: echo "Hello-Shantou!" 
  build:
   runs-on: ubuntu-latest
   steps: 
     - run: ls
     - uses: actions/checkout@v4.2.2
     - run: ls
